# -*- coding: utf-8 -*-
"""constants.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ch_k3jqUNDTX9fCFfcE7nxQkTpXG0A4G
"""

# constants.py

import os

# Directory paths
DATA_DIR = 'data'
IMAGES_DIR = os.path.join(DATA_DIR, 'images')


# File paths
MYNTRA_DATA_FILE = os.path.join(DATA_DIR, 'myntra_data.csv')
PRODUCT_CSV_FILE = os.path.join(DATA_DIR, 'myntra_sample_data.csv')